name: Lint

on:
  pull_request:

jobs:
  lint:
    name: lint
    runs-on: ubuntu-18.04

    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Setup node
        uses: actions/setup-node@v1
        with:
          node-version: 12

      - name: Run lint
        run: npm run lint
